name: mind_base
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_arch_core:
    git:
      url: https://github.com/GetArch/get_arch_core.git
      ref: v4.1
  provider_sidecar:
    git:
      url: https://github.com/Hu-Wentao/provider_sidecar
      ref: v1.3
  slowly:
    git:
      url: https://github.com/GetArch/slowly.git
      ref: v1.0
  get_sweet:
    git:
      url: https://github.com/GetArch/get_sweet.git
      ref: v1.0
  appwrite: 6.0.0
  dart_appwrite: 6.0.0
  freezed_annotation:
  go_router:
  adaptive_navigation:
  adaptive_breakpoints:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  pubspec_generator:
  injectable_generator:
  freezed:
  go_router_builder:

flutter:
  uses-material-design: true
